### ISSUE TITLE
No Total Count with gorm v1.23.1 and Preload

### ISSUE THREAD

**Issue by pitw** [soranoba/pageboy#15]
With gorm.io/gorm v1.23.1 TotalCount (https://github.com/soranoba/pageboy/blob/64023030e190dd911183b56c5e2a1906007fb5f6/pager.go#L22) stays 0.

Tested with SQLite (gorm.io/driver/sqlite v1.3.1)

**Comment by soranoba** [comment]
I have confirmed that it is working properly.
You can also confirm that it is working properly in the test.

https://github.com/soranoba/pageboy/blob/83095b558dd5237f3ec4defa508acb5e69257c15/tests/pager_test.go#L65-L82

The test can be run:
```shell
git clone git@github.com:soranoba/pageboy
docker-compose up -d
make test
```
```

**Comment by pitw** [comment]
Just checked my code. Problem exists only if **Preload()** in Gorm is used.
If no preload used everything work - else it shows TotalCount = 0.
Worked in previous versions.

**Comment by soranoba** [comment]
Thanks.

This issue is a side effect of this PR to gorm.
https://github.com/go-gorm/gorm/pull/5023

In other words, it occurs when using GORM v1.23.0 or later.

**Comment by soranoba** [comment]
I fixed. Please update v3.0.1
