### ISSUE TITLE
gen swagger cannot find pageboy.Pager

### ISSUE THREAD

**Issue by PittYao** [soranoba/pageboy#19]
hello soranoba 

-  throw error when i exe swag init . how can do this
`swag init cannot find pageboy.Pager `
![image](https://user-images.githubusercontent.com/26101917/156517314-286ff569-ffe2-49b6-b579-72c04f8532f4.png)

thanks

**Comment by soranoba** [comment]
You probably need to use `-parseDependency` or `-parseVendor`....

**Comment by PittYao** [comment]
> You probably need to use `-parseDependency` or `-parseVendor`....

try -parseVendor cannot gen
![image](https://user-images.githubusercontent.com/26101917/156730005-0abf2e1d-a2c1-44c8-a9ff-d35242a1ad9b.png)

try -parseDependency  no response
![image](https://user-images.githubusercontent.com/26101917/156730294-d821b041-f2b0-48eb-b49b-37c481ad2ee1.png)
