### ISSUE TITLE
WithConditions deprecated

### ISSUE THREAD

**Issue by pitw** [soranoba/pageboy#7]
The "WithConditions" Option in Session seems deprecated in latest Gorm V2:
https://github.com/go-gorm/gorm/blob/0c12a4c360e1f8b8569ffc9c29111a9abf58b492/gorm.go#L67

Causes error in your library here:
https://github.com/soranoba/pageboy/blob/c259ce7fc3088fc20a235db62d5b90c819cfc587/pager.go#L78

**Comment by soranoba** [comment]
Thank you. I will correspond.

ref: https://github.com/go-gorm/gorm/commit/26504f5caeb8c31dff62e8ddab68cee6b85a6580

**Comment by soranoba** [comment]
Supported in pageboy v2.1.0.

Please run to update:
```bash
go get -u github.com/soranoba/pageboy/v2@v2.1.0
```
